apiVersion: v1
kind: Service
metadata:
  name: ${APP_NAME}-service
  namespace: ${K8_NAMESPACE}
spec:
  type: NodePort
  selector:
    app: ${APP_NAME}
  ports:
  - port: 8200
    targetPort: 8200
    nodePort: ${NODE_PORT}
